name: fredgrotts_md3_demo
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-374.1.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^3.0.1
  material_color_utilities: ^0.2.0
  flex_color_scheme: ^6.1.1
  community_material_icon: ^5.9.55
  design_tools: ^0.3.0
  animations: ^2.0.7
  flutter_staggered_animations: ^1.1.1
  flutter_adaptive_scaffold: ^0.0.8
  rect_getter: ^1.1.0
  another_flushbar: ^1.12.29
  boxy: ^2.0.6+2
  flutter_layout_grid: ^2.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  # dart code metrics and extra lints
  dart_code_metrics: ^5.0.1
  # better lint
  lint: ^1.10.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/google_fonts/
